application:
  name: ${MS_NAME}
  version: ${MS_VERSION}

server:
  timezone: ${TZ}
infra:
  mongo:
    driver: ${MONGO_DRIVER}
    database:
      cluster: ${MONGO_CLUSTER}
      user: ${MONGO_USER}
      pass: ${MONGO_PASS}
      names:
        - ${MONGO_DB_NAME_NON}
        - ${MONGO_DB_NAME}

domain:
  apicpixel:
    ms-gateway:
      uri: ${MS_GATEWAY_URI}
      port: ${MS_GATEWAY_PORT}
    ms-service-base:
      uri: ${MS_BASE_SERVICE_URI}
      port: ${MS_BASE_SERVICE_PORT}
  valorant:
    url: ${VALORANT_URI}
    relative-paths:
      - agents
      - buddies
      - bundles
      - ceremonies
      - competitivetiers
      - contenttiers
      - contracts
      - currencies
      - events
      - gamemodes
      - gear
      - levelborders
      - maps
      - playercards
      - playertitles
      - seasons
      - sprays
      - themes
      - weapons
