application:
  name: ${db_version}
  version: ${db_version}

server:
  timezone: ${db_timezone}
infra:
  mongo:
    driver: ${db_driver}
    database:
      cluster: ${db_cluster}
      user: ${db_user}
      pass: ${db_pass}
      names:
        - ${db_name1}
        - ${db_name2}

domain:
  apicpixel:
    ms-gateway:
      uri: ${db_uri1}
      port: ${db_port1}
    ms-service-base:
      uri: ${db_uri2}
      port: ${db_port2}
  valorant:
    url: ${db_url}
    relative-paths:
      - agents
      - buddies
      - bundles
      - ceremonies
      - competitivetiers
      - contenttiers
      - contracts
      - currencies
      - events
      - gamemodes
      - gear
      - levelborders
      - maps
      - playercards
      - playertitles
      - seasons
      - sprays
      - themes
      - weapons
